name: audio_player_only
description: Standalone audio-only player.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  just_audio: 0.10.6
  just_audio_background: 0.0.1-beta.17
  photo_manager: 3.6.2

flutter:
  uses-material-design: true
